# Generated by Django 4.1.1 on 2022-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hearRate', models.DecimalField(decimal_places=3, max_digits=100)),
                ('oxygenSaturation', models.DecimalField(decimal_places=3, max_digits=100)),
                ('stressLevel', models.DecimalField(decimal_places=3, max_digits=100)),
            ],
        ),
    ]
