# Generated by Django 4.1.1 on 2022-09-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthMetrics', '0002_alter_user_hearrate_alter_user_oxygensaturation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
