# Generated by Django 4.1.1 on 2022-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthMetrics', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearRate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='oxygenSaturation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='stressLevel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
